stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3.6.3-openjdk-11
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-orders-storage2:12.1.0-SNAPSHOT.232
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-n6zpg:thunderjet-helmcharts-mod-orders-storage
      version: 0.1.32
      answers:
        image.repository: docker.dev.folio.org/mod-orders-storage2
        image.tag: 12.1.0-SNAPSHOT.232
        postJob.enabled: "true"
      name: mod-orders-storage
      targetNamespace: thunderjet
timeout: 60
notification: {}
